Test
Signed-off-by: Martin Vala <mavala@redhat.com>

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -49,7 +49,6 @@ jobs:
       run: |
         echo "global labels $OP_TEST_LABELS"
         bash <(curl -sL https://raw.githubusercontent.com/operator-framework/operator-test-playbooks/support/script_pull_target2/upstream/test/oprt.sh)
-        echo "AAA=${{ steps.op-traffic-light.outputs.op_test_modified_csvs }}"
     - name: Verify 
       id: verify
       env:
@@ -59,9 +58,9 @@ jobs:
       run: |
         echo ::set-output name=op_check_cosmetics::$OP_TEST_ALLOW_SERIOUS_CHANGES
         echo "xxx${OP_TEST_MODIFIED_CSVS_OTHERS}xxx"
-        [[ $OP_TEST_ALLOW_SERIOUS_CHANGES -eq 1 ]] && { echo "::set-output name=op_check_cosmetics::0"; exit 0; }
-        [ -n "$OP_TEST_MODIFIED_CSVS" ] && echo "::set-output name=op_check_cosmetics::1"
-        [ -n "$OP_TEST_MODIFIED_CSVS_OTHERS" ] && { echo "This is not cosmetics change !!! Following files cannot be changed : '$OP_TEST_MODIFIED_CSVS_OTHERS'"; exit 20; }
+        [[ $OP_TEST_ALLOW_SERIOUS_CHANGES -eq 1 ]] && { echo "::set-output name=op_check_cosmetics::0"; exit 0; } || true
+        [ -n "$OP_TEST_MODIFIED_CSVS" ] && echo "::set-output name=op_check_cosmetics::1" || true
+        [ -n "$OP_TEST_MODIFIED_CSVS_OTHERS" ] && { echo "This is not cosmetics change !!! Following files cannot be changed : '$OP_TEST_MODIFIED_CSVS_OTHERS'"; exit 20; } || true
 
     - name: Operator cosmetics change check
       id: op-cosmetics-change-check
