Test
Signed-off-by: Martin Vala <mavala@redhat.com>

diff --git a/.github/workflows/pull_request.yml b/.github/workflows/pull_request.yml
--- a/.github/workflows/pull_request.yml
+++ b/.github/workflows/pull_request.yml
@@ -58,11 +58,9 @@ jobs:
       run: |
         echo ::set-output name=op_check_cosmetics::0
         echo "xxx${OP_TEST_MODIFIED_CSVS_OTHERS}xxx"
-        
-        [ -z $OP_TEST_MODIFIED_CSVS ] || echo "::set-output name=op_check_cosmetics::1"
-        echo "aaa"
-        [ -z $OP_TEST_MODIFIED_CSVS_OTHERS ] || { echo "Not cosmetics change !!!"; }
-        [[ $OP_TEST_ALLOW_SERIOUS_CHANGES -eq 1 ]] && echo "::set-output name=op_check_cosmetics::0"
+        [[ $OP_TEST_ALLOW_SERIOUS_CHANGES -eq 1 ]] && { echo "::set-output name=op_check_cosmetics::0"; exit 0; }
+        [ -n "$OP_TEST_MODIFIED_CSVS" ] && echo "::set-output name=op_check_cosmetics::1"
+        [ -n "$OP_TEST_MODIFIED_CSVS_OTHERS" ] && { echo "This is not cosmetics change !!! Following files cannot be changed : '$OP_TEST_MODIFIED_CSVS_OTHERS'"; exit 20; }
 
     - name: Operator cosmetics change check
       id: op-cosmetics-change-check
